stages:     # List of stages for jobs, and their order of execution
  - test
  - build
  - publish
  - deploy
variables:
  IMAGE_NAME: $GITLAB_USER_LOGIN/$CI_PROJECT_NAME/$CI_COMMIT_BRANCH:latest
  MY_PASSWORD: $$Ali12345678
  MY_USER: aliiii0307

.job-cache:
  cache:  # Cache modules in between jobs
    key: 
      files:
        - package-lock.json
    paths:
      - .npm/
  before_script:
    - npm ci --cache .npm --prefer-offline
    
unit-test-job:   # This job runs in the test stage.
  stage: test 
  needs: []
  extends:
    - .job-cache
  only:
    - develop
    - merge_requests
    - main
  script:
    - npm run test
  dependencies: []
  artifacts:
    when: always
    paths:
      - jest-junit.xml
    reports:
      junit: jest-junit.xml
    expire_in: 1 day  

lint-test-job:
  stage: test
  needs: []
  extends:
    - .job-cache
  only:
    - develop
    - main
    - merge_requests
  dependencies: []
  script:
    - npm run lint
  artifacts:
    when: always
    paths:
      - eslint-junit.xml
    reports:
      junit: eslint-junit.xml
    expire_in: 1 day

develop server deploy job:      # This job runs in the deploy stage.
  stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
  only:
    - develop
    - main
  dependencies: []
  script:
    - .\deploy.ps1

# test server deploy job:
#   stage: deploy
#   tags: 
#    - release
#   only:
#     - release
#   dependencies: []
#   script: 
#     - sh deploy.sh

build image:
  image: docker
  stage: publish
  tags:
    - release
  services:
    - docker:dind
  before_script: 
    # - echo $CI_REGISTRY_PASSWORD |docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin
    - echo "$MY_PASSWORD" | docker login -u "$MY_USER" docker.arvancloud.ir --password-stdin
  script:
    # - echo "$CI_REGISTRY/"
    - docker build . --tag docker.arvancloud.ir/$IMAGE_NAME
    - docker push docker.arvancloud.ir/$IMAGE_NAME
