stages: 
  - install        # List of stages for jobs, and their order of execution
  - test
  - build
  - deploy

install:
  stage: install
  cache:  # Cache modules in between jobs
    key: 
      files:
        - package-lock.json
    paths:
      - .npm/
  script:
    - npm ci --cache .npm --prefer-offline

unit-test-job:   # This job runs in the test stage.
  stage: test 
  needs: 
    - job: install
  
  only:
    - develop
    - merge_requests
    - main
  script:
    - npm run test
  dependencies: []
  artifacts:
    when: always
    paths:
      - jest-junit.xml
    reports:
      junit: jest-junit.xml
    expire_in: 1 day  

lint-test-job:
  stage: test
  needs: 
    - job: install
  only:
    - develop
    - main
    - merge_requests
  dependencies: []
  script:
    - npm run lint
  artifacts:
    when: always
    paths:
      - eslint-junit.xml
    reports:
      junit: eslint-junit.xml
    expire_in: 1 day

deploy-job:      # This job runs in the deploy stage.
  stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
  only:
    - develop
    - main
  dependencies: []
  script:
    - .\deploy.ps1
