version: "3"
services:

  cache:
    image: redis
    restart: always
    ports:
      - '6379:6379'
    expose:
      - "1433"
#    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
#    volumes:
#      - cache:/data
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    expose:
      - "1433"
    environment:
      MSSQL_SA_PASSWORD_FILE: /run/secrets/sa_password
      ACCEPT_EULA: Y
    volumes:
      - sqlserver-files:/var/opt/mssql
    secrets:
      - sa_password




  redis:
      image: redis
      ports:
        - "6379:6379"
      expose:
        - "6379"


  nestjs-api:
    image: nestjs-api
    env_file:
      - .env
    ports:
      - "3000:3000"
#    depends_on:
#      - postgres
#    networks:
#      - postgres

#networks:
#  postgres:
#    driver: bridge
volumes:
  sqlserver-files:
    name: sqlserver-files
secrets:
  sa_password:
    file: sa_password.txt
