export enum VmStatusEnum {
  FAILED_CREATION = -1,
  UNRESOLVED = 0,
  RESOLVED = 1,
  SUSPENDED = 3,
  POWERED_ON = 4,
  WAITING_FOR_INPUT = 5,
  UNKNOWN = 6,
  UNRECOGNIZED = 7,
  POWERED_OFF = 8,
  INCONSISTENT_STATE = 9,
}
