export enum AclSubjectsEnum {
  Invoices = 'Invoices',
  Users = 'Users',
  AdminUser = 'AdminUser',
  Services = 'Services',
  AdminServices = 'AdminService',
  Default = 'Default',
  Ability = 'Ability',
  Auth = 'Auth',
  Budget = 'Budget',
  Datacenter = 'Datacenter',
  Vpc = 'Vpc',
  EdgeGateway = 'EdgeGateway',
  Nat = 'Nat',
  Vm = 'Vm',
  VmDetail = 'VmDetail',
  Vgpu = 'Vgpu',
  Tasks = 'Tasks',
  AdminTask = 'AdminTask',
  Networks = 'Networks',
  Ai = 'Ai',
  Vast = 'Vast',
  Tickets = 'Tickets',
  Group = 'Group',
  Robot = 'Robot',
  Company = 'Company',
  EntityLogs = 'EntityLogs',
}
